version: "3.1"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/.env
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file: ./server/.env
